In [5]:
import random

import requests
import json
from river.utils import numpy2dict
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from river import datasets
import numpy as np
from sklearn.metrics import accuracy_score
from collections import OrderedDict
from pprint import pprint

In [4]:
headers = {'Accept' : 'application/json', 'Content-Type' : 'application/json'}

def send(endpoint, params_dict = {}, url='http://127.0.0.1:5001/classifier'):
    return requests.get(url+endpoint, data=json.dumps(params_dict), headers=headers).json()


In [10]:
dataset_original = pd.read_csv(datasets.ImageSegments().path)
dataset_original['categorical_label'] = LabelEncoder().fit_transform(dataset_original['category'])

dataset_original

region-centroid-col  region-centroid-row  short-line-density-5  \
0                     218                  178              0.111111   
1                     113                  130              0.000000   
2                     202                   41              0.000000   
3                      32                  173              0.000000   
4                      61                  197              0.000000   
...                   ...                  ...                   ...   
2305                   30                  102              0.000000   
2306                  143                   24              0.000000   
2307                   80                   72              0.000000   
2308                   98                  133              0.000000   
2309                   19                  147              0.000000   

      short-line-density-2  vedge-mean  vegde-sd  hedge-mean  hedge-sd  \
0                      0.0    0.833333  0.547722    1.111109  0.544331   
1                      0.0    0.277778  0.250924    0.333333  0.365148   
2                      0.0    0.944448  0.772202    1.111112  1.025597   
3                      0.0    1.722222  1.781593    9.000000  6.749488   
4                      0.0    1.444444  1.515353    2.611111  1.925463   
...                    ...         ...       ...         ...       ...   
2305                   0.0    1.222222  0.118518    1.333333  0.800000   
2306                   0.0    1.277777  0.907406    0.888888  1.140749   
2307                   0.0    1.222223  1.003697    1.444444  1.167461   
2308                   0.0    0.555555  0.172133    0.388889  0.327731   
2309                   0.0    0.222222  0.074074    0.500000  0.077778   

      intensity-mean  rawred-mean  rawblue-mean  rawgreen-mean  exred-mean  \
0          59.629630    52.444443     75.222220      51.222220  -21.555555   
1           0.888889     0.000000      2.555556       0.111111   -2.666667   
2         123.037040   111.888885    139.777790     117.444440  -33.444443   
3          43.592594    39.555557     52.888890      38.333336  -12.111111   
4          49.592594    44.222220     61.555557      43.000000  -16.111110   
...              ...          ...           ...            ...         ...   
2305       20.259260    20.333334     25.000000      15.444445    0.222222   
2306      127.629630   117.666664    141.666670     123.555560  -29.888890   
2307       59.000000    51.333332     74.444440      51.222220  -23.000000   
2308        0.962963     0.000000      2.777778       0.111111   -2.888889   
2309        4.148148     3.888889      6.666666       1.888889   -0.777778   

      exblue-mean  exgreen-mean  value-mean  saturation-mean  hue-mean  \
0       46.777780    -25.222221   75.222220         0.318996 -2.040554   
1        5.000000     -2.333333    2.555556         1.000000 -2.123254   
2       50.222220    -16.777779  139.777790         0.199347 -2.299918   
3       27.888890    -15.777778   52.888890         0.266914 -1.998857   
4       35.888890    -19.777779   61.555557         0.302925 -2.022274   
...           ...           ...         ...              ...       ...   
2305    14.222222    -14.444445   25.000000         0.381059 -1.555097   
2306    42.111110    -12.222222  141.666670         0.169397 -2.349252   
2307    46.333332    -23.333334   74.444440         0.314606 -2.090221   
2308     5.444445     -2.555556    2.777778         1.000000 -2.123254   
2309     7.555555     -6.777778    7.000000         0.713228 -1.475643   

       category  categorical_label  
0          path                  4  
1       foliage                  2  
2           sky                  5  
3          path                  4  
4          path                  4  
...         ...                ...  
2305  brickface                  0  
2306        sky                  5  
2307     cement                  1  
2308    foliage                  2  
2309  brickface    

In [7]:
df_train = dataset_original[dataset_original['category'] != 'path']
category_path = dataset_original[dataset_original['category'] == 'path']

Y_train_simbolic = df_train.pop('category')
Y_train_numeric = df_train.pop('categorical_label')

df_train

region-centroid-col  region-centroid-row  short-line-density-5  \
1                     113                  130                   0.0   
2                     202                   41                   0.0   
6                     197                  229                   0.0   
7                      29                  111                   0.0   
8                       1                   81                   0.0   
...                   ...                  ...                   ...   
2305                   30                  102                   0.0   
2306                  143                   24                   0.0   
2307                   80                   72                   0.0   
2308                   98                  133                   0.0   
2309                   19                  147                   0.0   

      short-line-density-2  vedge-mean    vegde-sd  hedge-mean    hedge-sd  \
1                      0.0    0.277778    0.250924    0.333333    0.365148   
2                      0.0    0.944448    0.772202    1.111112    1.025597   
6                      0.0    1.388888    1.574073    1.166666    0.566666   
7                      0.0    0.388889    0.240741    0.611111    0.151852   
8                      0.0   12.166667  267.455540    9.222222  205.362960   
...                    ...         ...         ...         ...         ...   
2305                   0.0    1.222222    0.118518    1.333333    0.800000   
2306                   0.0    1.277777    0.907406    0.888888    1.140749   
2307                   0.0    1.222223    1.003697    1.444444    1.167461   
2308                   0.0    0.555555    0.172133    0.388889    0.327731   
2309                   0.0    0.222222    0.074074    0.500000    0.077778   

      intensity-mean  rawred-mean  rawblue-mean  rawgreen-mean  exred-mean  \
1           0.888889     0.000000      2.555556       0.111111   -2.666667   
2         123.037040   111.888885    139.777790     117.444440  -33.444443   
6          17.740740    14.111111     17.888890      21.222221  -10.888889   
7           5.407407     6.888889      6.333334       3.000000    4.444445   
8          21.333334    14.000000     30.555555      19.444445  -22.000000   
...              ...          ...           ...            ...         ...   
2305       20.259260    20.333334     25.000000      15.444445    0.222222   
2306      127.629630   117.666664    141.666670     123.555560  -29.888890   
2307       59.000000    51.333332     74.444440      51.222220  -23.000000   
2308        0.962963     0.000000      2.777778       0.111111   -2.888889   
2309        4.148148     3.888889      6.666666       1.888889   -0.777778   

      exblue-mean  exgreen-mean  value-mean  saturation-mean  hue-mean  
1        5.000000     -2.333333    2.555556         1.000000 -2.123254  
2       50.222220    -16.777779  139.777790         0.199347 -2.299918  
6        0.444444     10.444445   21.222221         0.335717  2.651605  
7        2.777778     -7.222222    6.888889         0.564153 -0.897859  
8       27.666666     -5.666666   30.555555         0.595282 -2.438409  
...           ...           ...         ...              ...       ...  
2305    14.222222    -14.444445   25.000000         0.381059 -1.555097  
2306    42.111110    -12.222222  141.666670         0.169397 -2.349252  
2307    46.333332    -23.333334   74.444440         0.314606 -2.090221  
2308     5.444445     -2.555556    2.777778         1.000000 -2.123254  
2309     7.555555     -6.777778    7.000000         0.713228 -1.475643  

[1980 rows x 18 columns]

In [10]:
np.unique(Y_train_simbolic)

array(['brickface', 'cement', 'foliage', 'grass', 'sky', 'window'],
      dtype=object)

# INICIO TREINOS

In [15]:
send('/init', {'type_model': 4})

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /classifier/init (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A99CA21508>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

In [9]:
for k, x in df_train.iterrows():
    send('/learn', {'x': numpy2dict(x.to_numpy()), 'y': int(Y_train_numeric.loc[k])})

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [289]:
predict = []
truth = []

for idx, x in df_train.iterrows():
    y_pred = send('/predict', {'type': 'one', 'x': numpy2dict(x.to_numpy())})['y_pred']
    predict.append(y_pred)
    y = Y_train_numeric.loc[idx]
    truth.append(y)
    #print('idx: ' + str(idx) + ' | y_pred: ' + str(y_pred) + ' | truth: ' + str(y))
    
print("Acurácia Supervisionada :" + str(accuracy_score(truth, predict)))

Acurácia Supervisionada :0.9702020202020202


In [297]:
y_pred_proba = send('/predict', {'type': 'proba', 'x': numpy2dict(df_train.iloc[1])})['y_pred']

y_pred_proba

{'0': 1.055450475836157e-176,
 '1': 5.4605231917914635e-33,
 '2': 2.455533682308092e-77,
 '3': 0.0,
 '5': 1.0,
 '6': 2.8646836585346085e-155}

In [240]:
idx = df_train.index[1]

print(dataset_original.iloc[idx]['category'])

sky


In [302]:
#QUERO SABER SE EXISTE ALGUMA LEITURA QUE TENHA A PROBA MAX < 0.5, OU  SEJA, INDECISAO

thresholds = np.arange(0.1, 1, 0.05)

for threshold in thresholds: 
    ind = 0
    for idx, x in df_train.iterrows():
        y_pred_proba = send('/predict', {'type': 'proba', 'x': numpy2dict(x.to_numpy())})['y_pred']

        max_proba = max(y_pred_proba.items(), key = lambda k : k[1])

        #indecisao
        if (max_proba[1] < threshold):           
            ind = ind+1
    print('{:.2f} : {:.2f}'.format(threshold, ind))

0.10 : 0.00
0.15 : 0.00
0.20 : 0.00
0.25 : 0.00
0.30 : 0.00
0.35 : 0.00
0.40 : 0.00
0.45 : 3.00
0.50 : 5.00
0.55 : 21.00
0.60 : 36.00
0.65 : 57.00
0.70 : 69.00
0.75 : 93.00
0.80 : 118.00
0.85 : 139.00
0.90 : 170.00
0.95 : 240.00


In [303]:
#VOU INSERIR A NOVA CLASSE

#VERIFICAR SE ELA ESTÁ SENDO CLASSIFICADO COMO UMA CLASSE CONHECIDA
#VERIFICAR SE ELA ESTÁ SENDO CLASSIFICADA COMO DESCONHECIDA (threshold < 0.3 de certeza na classe mais provavel)

X_test = category_path.iloc[:, :-2]

for threshold in thresholds: 
    ind = 0
    for idx, x in X_test.iterrows():
        y_pred_proba = send('/predict', {'type': 'proba', 'x': numpy2dict(x.to_numpy())})['y_pred']

        max_proba = max(y_pred_proba.items(), key = lambda k : k[1])
        if (max_proba[1] < threshold): #0.7 FOI O VALOR DE INDECISÃO QUE NAO CLASSIFICARIA INCORRETAMENTE AS NOVAS AMOSTRAS. ESSAS SERIAM ENVIADAS PARA OS EXPERTS
            #print('idx train: ' + str(idx))
            ind = ind+1

    print('{:.2f} : {:.2f}'.format(threshold, ind))

0.10 : 0.00
0.15 : 0.00
0.20 : 0.00
0.25 : 0.00
0.30 : 0.00
0.35 : 0.00
0.40 : 0.00
0.45 : 0.00
0.50 : 0.00
0.55 : 0.00
0.60 : 0.00
0.65 : 0.00
0.70 : 1.00
0.75 : 2.00
0.80 : 5.00
0.85 : 8.00
0.90 : 14.00
0.95 : 16.00


# METODOLOGIA

## DEFINIR DATASETS

S1 = {brickface, cement, foliage, grass, sky, window}

S1_1 = 70% S1 (de cada classe)

S1_2 = 30% S1 (de cada classe)

S2 = {path}

S2_1 = 30% S2

S2_2 = 70% S2

S3 = {S1_2 + S2_2)

## APLICAR METODOLOGIA

1. train S1_1

2. predict S2_1

3. cluster S2_1

4. train S2_1

5. validar S3 => métricas acurácia

6. Anomaly Detection (detector phase)


## preparando dados

In [12]:
from river import linear_model, metrics, multiclass, preprocessing
from river import ensemble
from river import neighbors
from river import tree
from sklearn.model_selection import train_test_split

In [13]:
S1 = dataset_original[dataset_original['category'] != 'path']

X_train, X_test, y_train, y_test = train_test_split(S1.iloc[:,:-2], S1.iloc[:, -1], stratify=S1.iloc[:, -1], test_size=0.3)

S1_1 = pd.concat([X_train,y_train], axis=1)

S1_2 = pd.concat([X_test, y_test], axis=1)

S2 = dataset_original[dataset_original['category'] == 'path']

X_train, X_test, y_train, y_test = train_test_split(S2.iloc[:,:-2], S2.iloc[:, -1], test_size=0.7)

S2_1 = pd.concat([X_train,y_train], axis=1)

S2_2 = pd.concat([X_test, y_test], axis=1)

S3 = pd.concat([S2_1, S2_2], axis=0)

### 1. train(S1_1)

In [9]:
S1_1_x = S1_1.iloc[:, :-1]
S1_1_y = S1_1.iloc[:, -1]

##### Criando o classificador RIVER KNN ADWIN_CLASSIFIER


In [10]:
classifier = ensemble.BaggingClassifier(
    model=(
            preprocessing.StandardScaler() |
            neighbors.KNNADWINClassifier()
    )
)

for k, x in S1_1_x.iterrows():
    classifier.predict_one(numpy2dict(x.to_numpy()))
    classifier = classifier.learn_one(numpy2dict(x.to_numpy()), int(S1_1_y.loc[k]))

##### Criando o classificador SCIKIT_MULTIFLOW KNN


In [11]:
from skmultiflow.lazy import KNNClassifier

classifier_knn_sk_mult = KNNClassifier(n_neighbors=8, max_window_size=2000, leaf_size=40)

for k, x in S1_1_x.iterrows():
    classifier_knn_sk_mult = classifier_knn_sk_mult.partial_fit(x.to_numpy().reshape(1, x.shape[0]), [int(S1_1_y.loc[k])])


Bad key "text.kerning_factor" on line 4 in
C:\Users\MARCELO\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution


### 2. predict(S2_1)

- nova categoria
- selecionar com THRESHOLD 0.95
- quantidade UNK -> K (erro)
- quantidade UNK -> UNK (acerto)
- enviar UNK -> UNK para Cluster


In [12]:
S2_1_x = S2_1.iloc[:, :-1]
S2_1_x.shape[0]

99

In [13]:
## 70% dos dados da classe 4 (path) foram classificadas, e devem ser marcadas como unknown

threshold = 0.95
classified_as_known = 0
DATASET_3 = []

for idx, x in S2_1_x.iterrows():
    y_pred_proba = classifier.predict_proba_one(numpy2dict(x.to_numpy()))

    max_proba = max(y_pred_proba.items(), key = lambda k : k[1])
    if (max_proba[1] < threshold): #indecisao
        DATASET_3.append(idx)
    else: #certeza
        classified_as_known = classified_as_known + 1


print('as know {:.2f}% : as unknown {:.2f}%'.format(classified_as_known/S2_1_x.shape[0]*100, len(DATASET_3)/S2_1_x.shape[0]*100))

as know 0.00% : as unknown 100.00%


In [14]:
S2_1_DATASET_3 = S2_1_x.loc[DATASET_3, :]

S2_1_DATASET_3

region-centroid-col  region-centroid-row  short-line-density-5  \
1424                  149                  182              0.111111   
777                   179                  162              0.000000   
454                   165                  186              0.000000   
942                    87                  196              0.111111   
1439                   38                  200              0.000000   
...                   ...                  ...                   ...   
718                   239                  160              0.000000   
1362                  254                  159              0.000000   
1579                   37                  189              0.000000   
767                   214                  161              0.000000   
2085                  123                  194              0.000000   

      short-line-density-2  vedge-mean  vegde-sd  hedge-mean    hedge-sd  \
1424                   0.0    3.111113  3.208783    7.000000    5.648992   
777                    0.0    1.944445  1.307408   14.055556    5.929622   
454                    0.0    2.555555  1.572919    2.000000    1.173788   
942                    0.0    1.333332  0.869228    2.222222    1.668887   
1439                   0.0    3.444445  2.125681    3.444445    1.204929   
...                    ...         ...       ...         ...         ...   
718                    0.0    1.833333  0.922221    5.944443    4.596297   
1362                   0.0    3.555555  7.540740   14.833333  152.700000   
1579                   0.0    1.388889  1.485184    5.722223   23.885176   
767                    0.0    3.722222  0.729634   11.500000   18.922234   
2085                   0.0    2.555556  1.784708    9.111109    7.713385   

      intensity-mean  rawred-mean  rawblue-mean  rawgreen-mean  exred-mean  \
1424       39.851852    37.222220     47.333332      35.000000   -7.888889   
777        40.296295    34.666668     49.222220      37.000000  -16.888890   
454        49.518520    45.111110     61.111110      42.333336  -13.222222   
942        61.592594    55.000000     75.666670      54.111110  -19.777779   
1439       55.962963    49.000000     70.222220      48.666668  -20.888890   
...              ...          ...           ...            ...         ...   
718        45.148148    37.888890     58.333332      39.222220  -21.777779   
1362       36.629630    31.333334     46.222220      32.333336  -15.888889   
1579       30.000000    27.111110     36.333336      26.555555   -8.666667   
767        40.444443    35.333336     49.666668      36.333336  -15.333333   
2085       60.814816    54.333332     74.888885      53.222220  -19.444445   

      exblue-mean  exgreen-mean  value-mean  saturation-mean  hue-mean  
1424    22.444445    -14.555555   47.333332         0.247790 -1.868277  
777     26.777779     -9.888889   49.222220         0.289652 -2.341198  
454     34.777780    -21.555555   61.111110         0.307257 -1.940813  
942     42.222220    -22.444445   75.666670         0.287526 -2.048736  
1439    42.777780    -21.888890   70.222220         0.309826 -2.080206  
...           ...           ...         ...              ...       ...  
718     39.555557    -17.777779   58.333332         0.352126 -2.162999  
1362    28.777779    -12.888889   46.222220         0.294845 -2.316872  
1579    19.000000    -10.333333   36.333336         0.265248 -2.050282  
767     27.666666    -12.333333   49.666668         0.298056 -2.198939  
2085    42.222220    -22.777779   74.888885         0.292382 -2.033605  

[99 rows x 18 columns]

### 3. cluster(S2_1)

#### Cluster classe 4 (path)

In [15]:
from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.preprocessing import StandardScaler

# precisa ser INCREMENTAL PCA
# precisa ser INCREMENTAL StandardScaler

pca = PCA(.95)

S2_1_cluster_pca = pd.DataFrame(pca.fit_transform(S2_1_DATASET_3).tolist())

S2_1_cluster_pca_ss = StandardScaler().fit_transform(S2_1_cluster_pca.to_numpy())

##### Incremental DBSTREAM

In [16]:
from river import cluster

y_pred_dbstream = []
dbstream = cluster.DBSTREAM(clustering_threshold = 2)

for x in S2_1_cluster_pca_ss:
    dbstream.learn_one(numpy2dict(x))
    y_pred_dbstream.append(dbstream.predict_one(numpy2dict(x)))

res =  [(el, y_pred_dbstream.count(el)) for el in y_pred_dbstream]
y_pred_dbstream_grouped = list(OrderedDict(res).items())
print(dbstream.n_clusters)

9


##### DenStream

In [17]:
denstream = cluster.DenStream()

y_pred_denstream = []
for x in S2_1_cluster_pca_ss:
    denstream.learn_one(numpy2dict(x))

for x in S2_1_cluster_pca_ss:
    y_pred_denstream.append(denstream.predict_one(numpy2dict(x)))

print(denstream.n_clusters)

1


##### DBSCAN

In [18]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(metric='manhattan').fit(S2_1_cluster_pca_ss)

dbscan_labels_list = dbscan.labels_.reshape(1, dbscan.labels_.shape[0]).tolist()[0]

res =  [(el, dbscan_labels_list.count(el)) for el in dbscan_labels_list]
y_pred_dbscan_grouped = list(OrderedDict(res).items())

print('Qtd Labels DBSCAN offline: ' + str(len(np.unique(dbscan.labels_))))

Qtd Labels DBSCAN offline: 6


#### TEDA Cloud

In [19]:
import numpy as np
import math
from numpy import linalg as LA
from scipy.spatial import distance


#### CLOUD ####
class Cloud:

    def __init__(self, sample=[], name='Default Class'):
        self.name = name
        self.var = 0
        self.n = 0
        self.covmat = []

        if (len(sample) > 0):
            self.mean = sample
            self.n = 1
            self.covmat = np.zeros((sample.shape[0], sample.shape[0]))

    def updateCloud(self, mu=[], var=0, n=0, covmat=[]):
        self.mean = mu
        self.var = var
        self.n = n
        self.covmat = covmat

    def addPoint(self, sample=[]):
        if (self.n == 0):
            self.n = 1
            self.mean = sample
            self.var = 0
            self.covmat = np.zeros((self.mean.shape[0], self.mean.shape[0]))
        else:
            self.n = self.n + 1
            self.mean = self.calculate_mean(sample, self.n)
            self.var = self.calculate_variance(sample, self.n, self.mean)
            self.covmat = self.calculate_variance_matrix(sample, self.n, self.mean)


    def calculateZeta(self, sample=[], similarity_measure='euclidean'):
        if self.n == 0:
            zeta = math.inf
            return zeta

        n_ = self.n + 1
        mean_ = self.calculate_mean(sample, n_)
        var_ = self.calculate_variance(sample, n_, mean_)
        covmat_ = self.calculate_variance_matrix(sample, n_, mean_)


        if (similarity_measure.lower() == 'euclidean'):
            ksi = np.maximum(self.calculate_eccentricity(sample, self.n, mean_, var_), 0.0001)
        else:
            ksi = np.maximum(self.calculate_eccentricity(sample, n_, mean_, var_, covmat_, 'mahalanobis'), 0.0001)

        zeta = ksi / 2
        return zeta

    def calculate_mean(self, sample, n):
        return ((n - 1) / n) * self.mean + (1 / n) * sample

    def calculate_variance(self, sample, n, mean):
        return ((n - 1) / n) * self.var + (1 / (n)) * LA.norm(sample - mean) ** 2

    def calculate_variance_matrix(self, sample, n, mean):
        a = (n - 1) / n
        b = a * self.covmat
        c = [sample - mean]
        d = np.transpose(c)
        e = (1 / n) * d    ##TALVEZ SEJA 1 / (n-1)

        f = b + e * c

        return f

    def calculate_eccentricity(self, sample, n, mean, variance, covmat = [], similarity_measure = 'euclidean'):

        a = 1 / n

        if (similarity_measure == 'euclidean'):
            b = [mean - sample]
            c = np.transpose(b)
            d = n * variance
            e = np.dot(b, c)
            f = e / d

            r = distance.euclidean(sample, mean)

            ksi = a + f
        else: # mahalanobis_formula => (sample - mean).T * covmat*-1 * (sample - mean)

            d_mahalanobis = np.zeros((1,1), dtype=float) + distance.mahalanobis(mean, sample, LA.pinv(covmat))**2

            h = n * len(mean) #nao entendi para que isso - parece a ponderacao do n elementos pela qtd de dimensoes
            m = d_mahalanobis / h

            ksi = a + m

        return ksi

###########################################################################
###########################################################################
################################ AUTOCLOUD ################################
###########################################################################
###########################################################################
class AutoCloud:

    def __init__(self, m = 2, similarity_measure = 'euclidean', auto_merge = True, display = False):
        self.k = 0
        self.cloudList = []
        self.predictions = {}
        self.predictions_by_sample = {}
        self.initialize_intersection_list()
        self.initialize_intersection_matrix()
        self.contMerge = 0
        self.dimension = 0
        self.similarityMeasure = similarity_measure
        self.autoMerge = auto_merge
        self.m = m
        self.display = display

    def run(self, sample = [], label = None):

        if (self.dimension == 0):
            self.dimension = sample.shape[0]
        else:
            if (self.dimension != sample.shape[0]):
                raise Exception('The dimension of the current data sample is different from the points read so far.')

        if (label != None): #para supervisionado - aqui temos também o Y (label) da amostra

            while (len(self.cloudList) < label): #cria a qtd de classes
                self.create_cloud(sample)

            self.cloudList[label - 1].addPoint(sample)
            self.k = self.k + 1

            self.initialize_intersection_list()
            self.membershipList = [0] * len(self.cloudList)
            self.membershipList[label - 1] = 1
            self.intersectionList[label - 1] = 1
            self.initialize_intersection_matrix()

            return label, self.membershipList

        else:
            self.k = self.k + 1
            self.initialize_intersection_list()

            if (self.k == 1):
                self.cloudList.append(Cloud(sample = sample, name = 'Class 1'))
                self.initialize_intersection_list()
                self.initialize_intersection_matrix()
                self.membershipList = [1]
            elif (self.k == 2):
                self.cloudList[0].addPoint(sample)
                self.membershipList = [1]
            elif (self.k >= 3):
                createCloud = True
                tauList = np.zeros((len(self.cloudList), 1))

                for i_cloud, cloud in enumerate(self.cloudList):
                    zeta = cloud.calculateZeta(sample, self.similarityMeasure) #??eccentricity | ?? norm_eccentricity
                    tau = 1 - zeta #??typicality
                    tauList[i_cloud] = tau

                    if (self.calculate_sample_belongs_to_cloud(zeta, cloud.n)):
                        cloud.addPoint(sample)
                        self.intersectionList[i_cloud] = 1
                        createCloud = False
                    else:
                        self.intersectionList[i_cloud] = 0

                self.membershipList = tauList / sum(tauList)

                ### NEW CLOUD ###
                if (createCloud == True):
                    self.create_cloud(sample)

        amax = np.amax(self.membershipList)
        where = np.where(self.membershipList == amax)
        y_label = where[0][0]+1

        if (self.autoMerge):
            self.mergeClouds()

        return y_label, self.membershipList

    def mergeClouds(self):
        i = 0

        i_end = len(self.cloudList) - 1
        while (i < i_end):

            merge = False

            j_end = np.arange(i + 1, len(self.cloudList)).reshape(-1)
            for j in j_end:
                if (self.intersectionList[i] == 1 and self.intersectionList[j] == 1):
                    self.intersectionMatrix[i,j] = self.intersectionMatrix[i,j] + 1

                ### recover information about clouds to be merged ###
                n_i = self.cloudList[i].n
                n_j = self.cloudList[j].n
                mean_i = self.cloudList[i].mean
                mean_j = self.cloudList[j].mean
                var_i = self.cloudList[i].var
                var_j = self.cloudList[j].var
                covmat_i = self.cloudList[i].covmat
                covmat_j = self.cloudList[j].covmat
                nint = self.intersectionMatrix[i,j]

                if (nint > (n_i - nint) or nint > (n_j - nint)):
                    ### merge
                    if (self.display):
                        print('Merging clouds ' + str(i+1) + ' and ' + str(j+1) + ' at instant ' + str(self.k))
                    ### calculate state of new cloud
                    n = n_i + n_j - nint
                    mean = ((n_i * mean_i) + (n_j * mean_j)) / (n_i + n_j)
                    var = ((n_i - 1) * var_i + (n_j - 1) * var_j) / (n_i + n_j - 2)
                    covmat = ((n_i - 1) * covmat_i + (n_j - 1) * covmat_j) / (n_i + n_j - 2)
                    ### create new cloud cloud ###
                    newCloud = Cloud()
                    newCloud.updateCloud(mean, var, n, covmat)
                    newCloud.name = 'Class ' + str(i+1) + '/' + str(j+1)

                    ### update intersection list ###
                    v_il1 = self.intersectionList[0: i]
                    v_il2 = np.array([1])
                    v_il3 = self.intersectionList[i + 1: j]
                    v_il4 = self.intersectionList[j + 1: np.size(self.intersectionList)]
                    self.intersectionList = np.concatenate((v_il1, v_il2, v_il3, v_il4), axis=None)

                    ## update cloud list ###
                    if (self.display):
                        print("Cloud (label) : " + str(i))
                    v_c1 = self.cloudList[0: i]
                    v_c2 = np.array([newCloud])
                    v_c3 = self.cloudList[i + 1: j]
                    v_c4 = self.cloudList[j + 1: np.size(self.cloudList)]
                    self.cloudList = np.concatenate((v_c1, v_c2, v_c3, v_c4), axis=None)

                    ### update intersection matrix ###
                    A = self.intersectionMatrix

                    #remover linha
                    vb1_0 = A[0: i, :]
                    vb2 = np.zeros((1, len(A)))
                    vb3 = A[i + 1: j, :]
                    vb4 = A[j + 1: len(A), :]
                    B = np.concatenate(([vb1_0, vb2, vb3, vb4]))

                    #remover coluna
                    vb1_1 = B[:, 0: i]
                    vb2 = np.zeros((len(B), 1))
                    vb3 = B[:, i + 1: j]
                    vb4 = B[:, j + 1: len(A)] ### acho que deveria ser LEN de B
                    B = np.concatenate(([vb1_1, vb2, vb3, vb4]), axis=1)

                    # calc nova coluna
                    col = (A[:, i] + A[:, j]) * (A[:, i] * A[:, j] != 0)
                    C = np.concatenate((col[0: j], col[j + 1: np.size(col)]))

                    # calc nova linha
                    lin = (A[i, :] + A[j, :]) * (A[i, :] * A[j, :] != 0)
                    L = np.concatenate((lin[0: j], lin[j + 1: np.size(lin)]))

                    #atualizar coluna
                    B[:,i] = C

                    #atualizar linha
                    B[i,:] = L

                    vb1_2 = A[[i], i+1 : j]
                    vb2 = A[i+1 : j, [j]]
                    vb3 = np.transpose(vb2)

                    B[[i], i+1 : j] = vb1_2 + vb3

                    self.intersectionMatrix = B

                    merge = True
                    self.contMerge = self.contMerge + 1
                    break

            if (merge == True):
                i = 1
            else:
                i = i + 1


    def initialize_intersection_matrix(self):
        if (len(self.cloudList) == 0):
            self.intersectionMatrix = np.zeros((1, 1))
        else:
            self.intersectionMatrix = np.zeros((len(self.cloudList), len(self.cloudList)))

    def initialize_intersection_list(self):
        if (len(self.cloudList) == 0):
            self.intersectionList = []
        else:
            self.intersectionList = [0] * len(self.cloudList)


    def calculateThreshold(self, s=None):
        if (self.similarityMeasure.lower() == 'euclidean'):
            th = (self.m ** 2 + 1) / (2 * (s))
        else:
            if (self.similarityMeasure.lower() == 'mahalanobis'):
                th = (self.m ** 2 + self.dimension) / (2 * (s) * self.dimension)

        threshold = th
        return threshold

    def create_cloud(self, sample):
        cloud_number = len(self.cloudList) + 1
        if (self.display):
            print('Creating cloud ' + str(cloud_number) + ' at instant ' + str(self.k))

        self.cloudList = np.append(self.cloudList, [Cloud(sample, 'Class ' + str(cloud_number))], axis=0)
        self.intersectionList.append(1)
        self.expand_intersection_matrix_with_zeros()

    def calculate_sample_belongs_to_cloud(self, zeta, cloud_n):
        return (zeta < math.inf and zeta <= self.calculateThreshold(cloud_n))

    def expand_intersection_matrix_with_zeros(self):
        self.intersectionMatrix = np.pad(self.intersectionMatrix, ((0, 1), (0, 1)), mode='constant', constant_values=0)

In [20]:
clusterer = AutoCloud(2, 'mahalanobis')

output = [0] * (S2_1_cluster_pca_ss.shape[0])

for k, sample in pd.DataFrame(S2_1_cluster_pca_ss).iterrows():
    y, _ = clusterer.run(sample)
    output.append(y)

print(len(np.unique(output)))

3


#### Cluster class 1 , 4 (foliage, path)

In [83]:
pca = PCA(.95)

S2_1_4_cluster_pca = pd.DataFrame(pca.fit_transform(pd.concat([S2_1_DATASET_3,S1_1[S1_1['categorical_label'] == 1].iloc[0:94, :-1]])).tolist())

S2_1_4_cluster_pca_ss = StandardScaler().fit_transform(S2_1_4_cluster_pca.to_numpy())

In [198]:
from river import cluster

y_pred_dbstream = []
dbstream_1_4 = cluster.DBSTREAM(clustering_threshold = 2)

for x in S2_1_4_cluster_pca_ss:
    dbstream_1_4.learn_one(numpy2dict(x))
    y_pred_dbstream.append(dbstream_1_4.predict_one(numpy2dict(x)))

print(dbstream_1_4.n_clusters)

13


In [199]:
denstream_1_4 = cluster.DenStream()

y_pred_denstream = []
for x in S2_1_4_cluster_pca_ss:
    denstream_1_4.learn_one(numpy2dict(x))

for x in S2_1_4_cluster_pca_ss:
    y_pred_denstream.append(denstream_1_4.predict_one(numpy2dict(x)))

print(denstream_1_4.n_clusters)

1


In [91]:
from sklearn.cluster import DBSCAN

dbscan_1_4 = DBSCAN(metric='chebyshev').fit(S2_1_4_cluster_pca_ss)

print('Qtd Labels DBSCAN offline: ' + str(len(np.unique(dbscan_1_4.labels_))))
print(dbscan_1_4.labels_)

Qtd Labels DBSCAN offline: 4
[-1  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 -1  0  0
  0  0  0 -1  0 -1  0  0  0  0  0  0 -1 -1 -1  0 -1  0  0  0  0  0  0  0
  0  0  0  0  0  0 -1  0  0 -1  0  0  0 -1  0  0 -1  0  0  0  0 -1 -1  0
 -1  0 -1  0  0 -1  0  0 -1  0  0  0  0 -1  0  0  0 -1  0  0  0 -1  0 -1
  0  0  2 -1  2  1 -1  1  1  1  1 -1  2 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1
  1  1 -1  2 -1  1 -1  2 -1 -1  1  2 -1 -1 -1 -1  1 -1  1  1  1 -1 -1 -1
 -1  1  2  2 -1  2  1 -1  1 -1  1  2  1  2  2 -1 -1  1 -1 -1  1 -1  1  1
  1  2 -1  1 -1  1  1 -1  1  1 -1  1  1  1  1  2 -1  1  2 -1  1  2  2  2]


#### TEDA Cloud

In [201]:
autocloud_1_4 = AutoCloud(2, 'mahalanobis')

output = [0] * (S2_1_4_cluster_pca_ss.shape[0])

for k, sample in pd.DataFrame(S2_1_4_cluster_pca_ss).iterrows():
    y, _ = autocloud_1_4.run(sample)
    output.append(y)

print(len(np.unique(output)))

9


### 4. train_classifier(S2_1)

#### clusterer DBSTREAM -> CLASSIFIER

In [21]:
## COPIEI O CONTEUDO DO ENDPOINT KNOWN E VOU FAZER NA MÃO
## POIS NAO TERIA COMO REVERTER O PCA, POIS NÃO TENHO A
## REFERENCIA NO ARQUIVO _INIT_.PY

slice_factor = 0.2

# parameters
cluster = 3
_class = 35

# obter centro cluster 0
# obter samples do cluster 0
# calcular os __slice_factor__ mais proximos
# identificar que sao os samples no vetor original pré PCA e SS (posso utilizar o DB como apoio)
# enviar os samples para o CLASSIFICADOR

In [22]:
#obter centro do cluster X
cluster_center = dbstream.centers[cluster]

In [23]:
from scipy.spatial import distance
from river.utils import dict2numpy
import math

# pegar as keys dos samples para o cluster selecionado
cluster_key_samples = [key for key, value in enumerate(y_pred_dbstream) if value == cluster]

# pegar os samples para o cluster selecionado
cluster_samples = S2_1_cluster_pca_ss[cluster_key_samples]

# calcular distancias para cada sample
distances = []
for sample in cluster_samples:
    distances.append(distance.euclidean(dict2numpy(cluster_center), sample))

distances_unsorted = distances.copy()
distances.sort()

qty_distances_retrieve = math.ceil(len(distances) * slice_factor)
distances_retrieve = distances[: qty_distances_retrieve]

closest_samples_keys = [idx for idx, element in enumerate(distances_unsorted) if element in distances_retrieve]

#x = [cluster_samples[k] for k in closest_samples_keys]

#cluster_key_samples[[closest_samples_keys]]
cluster_key_samples_closest = [cluster_key_samples[v] for k, v in enumerate(closest_samples_keys)]

S2_1_DATASET_3_numpy =  S2_1_DATASET_3.to_numpy()[cluster_key_samples_closest]

# treinando INCREMENTALMENTE o classificador

for k, x in enumerate(S2_1_DATASET_3_numpy):
    classifier.learn_one(numpy2dict(x), _class)

#### predict (S2_2)

In [24]:
y_pred = []
for k, x in S2_2.iloc[:, :-1].iterrows():
    y_pred.append(classifier.predict_one(numpy2dict(x.to_numpy())))

In [25]:
res =  [(el, y_pred.count(el)) for el in y_pred]
predicts_grouped = list(OrderedDict(res).items())

for k, x in enumerate(predicts_grouped):
    if x[0] == 35:
        print('Acc DBSTREAM: ' + str(x[1] / S2_2.shape[0] * 100) + '%')

Acc DBSTREAM: 3.463203463203463%


### clusterer DBSCAN -> CLASSIFIER

In [26]:
cluster = 1
_class = 35

cluster_key_samples_match = [k for k, v in enumerate(dbscan.labels_) if v == cluster]

S2_1_cluster_send_classifier = S2_1_DATASET_3.iloc[cluster_key_samples_match]

# treinando INCREMENTALMENTE o classificador

for k, x in S2_1_cluster_send_classifier.iterrows():
    classifier.learn_one(numpy2dict(x.to_numpy()), _class)

#### predict (S2_2)

In [27]:
y_pred = []
for k, x in S2_2.iloc[:, :-1].iterrows():
    y_pred.append(classifier.predict_one(numpy2dict(x.to_numpy())))

In [28]:
res =  [(el, y_pred.count(el)) for el in y_pred]
predicts_grouped = list(OrderedDict(res).items())

for k, x in enumerate(predicts_grouped):
    if x[0] == 35:
        print('Acc KNN RIVER: ' + str(x[1] / S2_2.shape[0] * 100) + '%')

Acc KNN RIVER: 38.52813852813853%


### clusterer DBSCAN -> CLASSIFIER KNN SCIKIT_MULTIFLOW

In [29]:
cluster = 1
_class = 35

cluster_key_samples_match = [k for k, v in enumerate(dbscan.labels_) if v == cluster]

S2_1_cluster_send_classifier = S2_1_DATASET_3.iloc[cluster_key_samples_match]

# treinando INCREMENTALMENTE o classificador

for k, x in S2_1_cluster_send_classifier.iterrows():
    classifier_knn_sk_mult.partial_fit(x.to_numpy().reshape(1, x.shape[0]), [_class])

#### predict (S2_2)

In [30]:
y_pred = []
for k, x in S2_2.iloc[:, :-1].iterrows():
    y_pred.append(classifier_knn_sk_mult.predict(x.to_numpy().reshape(1,x.shape[0]))[0])

In [31]:
res =  [(el, y_pred.count(el)) for el in y_pred]
predicts_grouped = list(OrderedDict(res).items())

for k, x in enumerate(predicts_grouped):
    if x[0] == 35:
        print('Acc KNN SCIKIT MULTILEARN: ' + str(x[1] / S2_2.shape[0] * 100) + '%')

Acc KNN SCIKIT MULTILEARN: 48.917748917748916%


# 6. DETECTOR PHASE

brickface (0) -> NORMAL

In [15]:
NORMAL_x_train = S1_1.loc[S1_1['categorical_label'] == 0].iloc[:, :-1]
NORMAL_x_test = S1_2.loc[S1_2['categorical_label'] == 0].iloc[:, :-1]

### OvsO

In [17]:
from river import anomaly
from river import preprocessing
from river import multiclass
from river import linear_model
from river import tree
from sklearn.preprocessing import MinMaxScaler

scaler = preprocessing.StandardScaler()
ovo = multiclass.OneVsOneClassifier(tree.HoeffdingAdaptiveTreeClassifier())
model_ovo = scaler | ovo

In [12]:
for k, x in NORMAL_x_train.iterrows():
    model_ovo.learn_one(numpy2dict(x.to_numpy()), 0)

In [13]:
for k, x in NORMAL_x_test.iterrows():
    pprint(model_ovo.predict_one(numpy2dict(x.to_numpy())))

Error evaluating: thread_id: pid_13652_id_1486881238472
frame_id: 1487217562744
scope: FRAME
attrs: votes	default_factory
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\DataSpell 213.5352.7\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 286, in resolve_compound_variable_fields
    return _typeName, resolver.get_dictionary(VariableWithOffset(var, offset) if offset else var)
AttributeError: 'NoneType' object has no attribute 'get_dictionary'


KeyboardInterrupt: 

In [ ]:
from river import synth
from river import evaluate
from river import metrics
from river import tree

gen = synth.ConceptDriftStream(stream=synth.SEA(seed=42, variant=0),drift_stream=synth.SEA(seed=42, variant=1),seed=1, position=500, width=50)
# Take 1000 instances from the infinite data generator
dataset = iter(gen.take(1000))

model = tree.HoeffdingAdaptiveTreeClassifier(grace_period=100,split_confidence=1e-5,leaf_prediction='nb',
                                             nb_threshold=10,seed=0)

metric = metrics.Accuracy()

evaluate.progressive_val_score(dataset, model, metric)


### HalfSpaceTree RIVER

In [98]:
from river import preprocessing

#HIPERPARÂMETROS
qty_pred_normal = 0
threshold = 0.75

minmax_scaler = MinMaxScaler()
model = anomaly.HalfSpaceTrees(seed=42, window_size=2, height=2, n_trees=5)

for k, x in NORMAL_x_train.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.partial_fit(data).transform(data)

    model = model.learn_one(numpy2dict(scaled[0]))

for k, x in NORMAL_x_test.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.transform(data)

    score = model.score_one(numpy2dict(scaled[0]))

    if (score >= threshold):
        qty_pred_normal = qty_pred_normal+1

pprint('Identificou ' + str(qty_pred_normal/len(NORMAL_x_test)*100) + '% de amostras NORMAIS corretamente')

qty_pred_falha = 0
for k, x in S3.iloc[:, :-1].iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.transform(data)

    score = model.score_one(numpy2dict(scaled[0]))

    if (score < threshold):
        qty_pred_falha = qty_pred_falha+1

pprint('Identificou ' + str(qty_pred_falha/len(S3)*100) + '% de amostras de falhas corretamente')

'Identificou 1.0101010101010102% de amostras NORMAIS corretamente'
'Identificou 86.36363636363636% de amostras de falhas corretamente'


### Half Space Tree Sklearn Multiflow

In [29]:
from skmultiflow.anomaly_detection import HalfSpaceTrees

qty_pred_normal = 0

minmax_scaler = MinMaxScaler()
half_space_trees = HalfSpaceTrees(random_state=1, anomaly_threshold=0.5, window_size=2)

for k, x in NORMAL_x_train.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.partial_fit(data).transform(data)

    half_space_trees.partial_fit(scaled)

for k, x in NORMAL_x_test.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.transform(data)

    y_pred = half_space_trees.predict(scaled)

    if (y_pred == 0):
        qty_pred_normal = qty_pred_normal+1

pprint('Identificou ' + str(qty_pred_normal/len(NORMAL_x_test)*100) + '% de amostras NORMAIS corretamente')

qty_pred_falha = 0
for k, x in S3.iloc[:, :-1].iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])
    scaled = minmax_scaler.transform(data)

    y_pred = half_space_trees.predict(scaled)

    if (y_pred == 1):
        qty_pred_falha = qty_pred_falha+1

pprint('Identificou ' + str(qty_pred_falha/len(S3)*100) + '% de amostras de falhas corretamente')



'Identificou 0.0% de amostras NORMAIS corretamente'
'Identificou 100.0% de amostras de falhas corretamente'


### Naive Bayes Sklearn Multiflow

In [59]:
from skmultiflow.bayes import NaiveBayes
from sklearn.decomposition import PCA, IncrementalPCA
from sklearn.preprocessing import StandardScaler


pca = PCA(.95)
S1_x_pca = pd.DataFrame(pca.fit_transform(S1.iloc[:, :-2]).tolist())
S1_x_pca_ss = pd.DataFrame(StandardScaler().fit_transform(S1_x_pca.to_numpy()))

S1_x2_pca = pd.DataFrame(pca.fit_transform(S3.iloc[:, :-1]).tolist())
S1_x2_pca_ss = pd.DataFrame(StandardScaler().fit_transform(S1_x2_pca.to_numpy()))

qty_pred_normal = 0
threshold = 0.5

minmax_scaler = MinMaxScaler()
nb = NaiveBayes()

for k, x in S1_x_pca_ss.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])

    nb.partial_fit(data, [0])

for k, x in S1_x_pca_ss.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])

    y_pred = nb.predict(data)

    if (y_pred == 0):
        qty_pred_normal = qty_pred_normal+1

pprint('Identificou ' + str(qty_pred_normal/len(S1.iloc[:, -2])*100) + '% de amostras NORMAIS corretamente')

qty_pred_falha = 0
for k, x in S1_x2_pca_ss.iterrows():
    x_np = x.to_numpy()
    data = x_np.reshape(1, x_np.shape[0])

    y_pred = nb.predict(data)[0]

    if (y_pred != threshold):
        qty_pred_falha = qty_pred_falha+1

pprint('Identificou ' + str(qty_pred_falha/len(S3)*100) + '% de amostras de falhas corretamente')

'Identificou 100.0% de amostras NORMAIS corretamente'
'Identificou 100.0% de amostras de falhas corretamente'


### OneClass SVM - SUPERVISIONADO (teste)

Pode ser utilizado como linha de base para comparação desta fase!

Resultados foram excelentes

In [101]:
from sklearn.svm import OneClassSVM

ocsvm = OneClassSVM(gamma='auto')

ocsvm.fit(S2_2.iloc[:, :-1])

correct_normal = ocsvm.predict(S2_1.iloc[:, :-1])

correct_normal_identified = 0
for k, x in enumerate(correct_normal):
    if (x == -1):
        correct_normal_identified = correct_normal_identified+1

pprint('Identificou ' + str(correct_normal_identified/len(correct_normal)*100) + '% de amostras de normais corretamente')

predicts_failures = ocsvm.predict(S1.iloc[:, :-2])

correct_failures_identified = 0
for k, x in enumerate(predicts_failures):
    if (x == -1):
        correct_failures_identified = correct_failures_identified+1

pprint('Identificou ' + str(correct_failures_identified/len(predicts_failures)*100) + '% de amostras de falhas corretamente')



'Identificou 88.88888888888889% de amostras de normais corretamente'
'Identificou 100.0% de amostras de falhas corretamente'


###### Testes do Min Max SCALER Incremental

In [1]:
# MinMax Scaler RIVER
# FUNCIONA SOMENTE PARA 1 DIMENSAO

X = [{'x': 0.0, 'y': 9}, {'x': 0.0, 'y': 4.5}, {'x': 5, 'y': 4.5}, {'x': 2.5, 'y': 4.5}]

scaler = preprocessing.MinMaxScaler()

for x in X:
    pprint(scaler.learn_one(x).transform_one(x))

NameError: name 'preprocessing' is not defined

In [560]:
# MinMax Scikit Multiflow
#NÃO FUNCIONA CORRETAMENTE

from skmultiflow import transform

wss = transform.WindowedMinmaxScaler(window_size=1)

data = np.array([
    [[0.0, 10]],
    [[0.0, 5]],
    [[0.0, 0]],
    [[0.0, 5]],
    [[0.0, 5]],
    [[0.0, 20]],
    [[10, 20]],
    [[5, 5]]
])

for k, v in enumerate(data):
    pprint(wss.partial_fit_transform(data[k]))

array([[ 0., 10.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])


In [574]:
# MinMax Scikit Learning
# FUNCIONOU PERFEITO

from sklearn.preprocessing import MinMaxScaler

data = np.array([
                [[0.0, 10]],
                [[0.0, 5]],
                [[0.0, 0]],
                [[0.0, 5]],
                [[0.0, 5]],
                [[0.0, 20]],
                [[10, 20]],
                [[5, 5]]
])

sk_scaler = MinMaxScaler()

for k, v in enumerate(data):
    pprint(sk_scaler.partial_fit(data[k]).transform(data[k]))


array([[0., 0.]])
array([[0., 0.]])
array([[0., 0.]])
array([[0. , 0.5]])
array([[0. , 0.5]])
array([[0., 1.]])
array([[1., 1.]])
array([[0.5 , 0.25]])
